version: '2.1'
services:
    redis:
        image: redis:6.0-alpine
        ports:
            - "6379:6379"
    mysql:
        image: mysql:5.7
        command: ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_unicode_ci", "--explicit_defaults_for_timestamp"]
        env_file:
            - .env
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "3306:3306"
    mongo:
      image: mongo:4.4.2
        container_name: mongodb
        hostname: mongodb
        restart: always
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        expose:
            - 6016
        ports:
            - "27017:27017"

    webserver:
        build: .
        container_name: airflow_local
        depends_on:
            - mysql
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
